# ================== General ==================
Id: Python.Python
Name: Python
Publisher: Python
Author: Python
Description: Python is a programming language that lets you work more quickly and integrate your systems more effectively.
#AppMoniker: 
Tags: python, python3, programming language, script, glue language
FileExtensions: py,pyw,pyc,pyo
#Protocols: 
#Commands:

# ================== License ==================
Homepage: https://www.python.org
License: PSF LICENSE AGREEMENT FOR PYTHON
LicenseUrl: https://docs.python.org/3/license.html

# ================= Installer =================
Version: 3.2.5
InstallerType: msi
Installers:
  - Arch: x64
    Url: https://www.python.org/ftp/python/3.2.5/python-3.2.5.amd64.msi
    Sha256: c75c2326a79edfa027fc22a9f28dcaac7f88e9969b91a391f4b211386fe6b8fc
    #Switches:
    #  Silent: 
    #  SilentWithProgress:
