# ================== General ==================
Id: Python.Python
Name: Python
Publisher: Python
Author: Python
Description: Python is a programming language that lets you work more quickly and integrate your systems more effectively.
#AppMoniker: 
Tags: python, python3, programming language, script, glue language
FileExtensions: py,pyw,pyc,pyo
#Protocols: 
#Commands:

# ================== License ==================
Homepage: https://www.python.org
License: PSF LICENSE AGREEMENT FOR PYTHON
LicenseUrl: https://docs.python.org/3/license.html

# ================= Installer =================
Version: 3.2.4
InstallerType: msi
Installers:
  - Arch: x64
    Url: https://www.python.org/ftp/python/3.2.4/python-3.2.4.amd64.msi
    Sha256: 60178a5d37e54e2cc2bcf2721467a03daf6a483eca80fb2f7e19d2f92cd15e7b
    #Switches:
    #  Silent: 
    #  SilentWithProgress:
