# ================== General ==================
Id: Python.Python
Name: Python
Publisher: Python
Author: Python
Description: Python is a programming language that lets you work more quickly and integrate your systems more effectively.
#AppMoniker: 
Tags: python, python3, programming language, script, glue language
FileExtensions: py,pyw,pyc,pyo
#Protocols: 
#Commands:

# ================== License ==================
Homepage: https://www.python.org
License: PSF LICENSE AGREEMENT FOR PYTHON
LicenseUrl: https://docs.python.org/3/license.html

# ================= Installer =================
Version: 3.3.5
InstallerType: msi
Installers:
  - Arch: x64
    Url: http://www.python.org/ftp/python/3.3.5/python-3.3.5.amd64.msi
    Sha256: 4be9dfe84fd5e0bc183fc24680a95a77a86aef21e9989d834084ee6dcc5b2cab
    #Switches:
    #  Silent: 
    #  SilentWithProgress: 
