# ================== General ==================
Id: Python.Python
Name: Python
Publisher: Python
Author: Python
Description: Python is a programming language that lets you work more quickly and integrate your systems more effectively.
#AppMoniker: 
Tags: python, python3, programming language, script, glue language
FileExtensions: py,pyw,pyc,pyo
#Protocols: 
#Commands:

# ================== License ==================
Homepage: https://www.python.org
License: PSF LICENSE AGREEMENT FOR PYTHON
LicenseUrl: https://docs.python.org/3/license.html

# ================= Installer =================
Version: 3.3.4
InstallerType: msi
Installers:
  - Arch: x64
    Url: https://www.python.org/ftp/python/3.3.4/python-3.3.4.amd64.msi
    Sha256: 4ea8198da0d132a0cb78a034539ef4cda978b5ac7790b2420f34dc91309becae
    #Switches:
    #  Silent: 
    #  SilentWithProgress: 
