# ================== General ==================
Id: Python.Python
Name: Python
Publisher: Python
Author: Python
Description: Python is a programming language that lets you work more quickly and integrate your systems more effectively.
#AppMoniker: 
Tags: python, python3, programming language, script, glue language
FileExtensions: py,pyw,pyc,pyo
#Protocols: 
#Commands:

# ================== License ==================
Homepage: https://www.python.org
License: PSF LICENSE AGREEMENT FOR PYTHON
LicenseUrl: https://docs.python.org/3/license.html

# ================= Installer =================
Version: 3.5.4
InstallerType: exe
Installers:
  - Arch: x64
    Url: https://www.python.org/ftp/python/3.5.4/python-3.5.4-amd64.exe
    Sha256: 9b7741cc32357573a77d2ee64987717e527628c38fd7eaf3e2aaca853d45a1ee
    Switches:
      Silent: /Quiet
      SilentWithProgress: /Passive
      Custom: PrependPath=1
