Id: Microsoft.XMLNotepad
Author: Chris Lovett
Publisher: Microsoft Corporation
Name: XML Notepad
Version: 2.8.0.26
License: Copyright (C) Microsoft Corporation
LicenseUrl: https://github.com/microsoft/XmlNotepad/blob/master/LICENSE
MinOSVersion: 10.0.18362.0
FileExtensions: xml
AppMoniker: xmlnotepad
Tags: xml editor, xml
Description: XML Notepad is a lightweight and fast tool for editing XML documents.
Homepage: https://github.com/microsoft/xmlnotepad
Installers:
  - Arch: Neutral
    InstallerType: MSIX
    Url: https://lovettsoftwarestorage.blob.core.windows.net/downloads/XmlNotepad.Net/2.8.0.26/XmlNotepadPackage_2.8.0.26_Test/XmlNotepadPackage_2.8.0.26_AnyCPU.msixbundle
    Sha256: ae50108e5298af99e807a347d561bbb3655fddd204533b6656cd0ce5a0f61960
    Language: en
