---

Id: dnGrep.dnGrep
Version: v2.9.326.0
Name: dnGrep
Publisher: dnGrep
License: GPL-2.0
AppMoniker: dnGrep
Tags: grep, search
Description: dnGrep allows you to search across files with easy-to-read results. Search through text files, Word and Excel documents, PDFs, and archives using text, regular expression, XPath, and phonetic queries. dnGrep includes search-and-replace, whole-file preview, right-click search in File Explorer, and much more.
Homepage: http://dngrep.github.io/
Installers:
  - Arch: x64
    Url: https://github.com/dnGrep/dnGrep/releases/download/v2.9.326.0/dnGREP.2.9.326.x64.msi
    Sha256: 601B39DAC7E52D9158990227CCF00E62A34739846419FA91E4ED84AC2C51720A
    InstallerType: msi
