# ================== General ==================
Id: Microsoft.PowerShell
Name: PowerShell
Publisher: Microsoft Corporation
Author: Microsoft Corporation
Description: PowerShell is a cross-platform (Windows, Linux, and macOS) automation and configuration tool/framework that works well with your existing tools and is optimized for dealing with structured data (e.g. JSON, CSV, XML, etc.), REST APIs, and object models. It includes a command-line shell, an associated scripting language and a framework for processing cmdlets.
AppMoniker: pwsh
Tags: powershell,pwsh,shell,dotnet
FileExtensions: ps1
#Protocols: 
Commands: pwsh

# ================== License ==================
Homepage: https://microsoft.com/PowerShell
License: MIT
LicenseUrl: https://github.com/PowerShell/PowerShell/blob/master/LICENSE.txt

# ================= Installer =================
Version: 7.0.6
InstallerType: msi
Installers:
  - Arch: x64
    Url: https://github.com/PowerShell/PowerShell/releases/download/v7.0.6/PowerShell-7.0.6-win-x64.msi
    Sha256: 586E3B3D6A706A850C8883FCB1FDEA33C65402F82E3AB8EC8C877E7BF0098327
    #Switches:
    #  Silent: 
    #  SilentWithProgress: 
