Id: Microsoft.PowerShell
Version: 7.1.3
Name: PowerShell
Publisher: Microsoft
Homepage: https://microsoft.com/PowerShell
License: MIT
Description: PowerShell is a cross-platform (Windows, Linux, and macOS) automation and configuration tool/framework that works well with your existing tools and is optimized for dealing with structured data (e.g. JSON, CSV, XML, etc.), REST APIs, and object models. It includes a command-line shell, an associated scripting language and a framework for processing cmdlets.
AppMoniker: pwsh
Tags: powershell, pwsh
Commands: pwsh
Installers:
  - Arch: x64
    Url: https://github.com/PowerShell/PowerShell/releases/download/v7.1.3/PowerShell-7.1.3-win-x64.msi
    InstallerType: MSI
    Sha256: 459642D8B6D69F643794DF8394F28191F43E5ED35472899C4F0D8424F6D1317C
